# Gradle properties.
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8

# System properties.
# Required to use the multi-release jars as dependencies with the java-library plugin:
systemProp.org.gradle.java.compile-classpath-packaging=true

# Project properties
kotlin.code.style=official
group=com.clickhouse
version=0.9.4-SNAPSHOT